name = "CurveFit"
uuid = "5a033b19-8c74-5913-a970-47c3779ef25c"
authors = ["Paulo Jos√© Saiz Jabardo <pjabardo@gmail.com> and contributors"]
version = "0.3.5"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"

[compat]
Polynomials = "1.0, 1.2, 2.0"
julia = "1.0, 1.6"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Test"]
